[pytest]
testpaths = tests
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning:multiprocessing
    ignore:pkg_resources is deprecated:UserWarning
    ignore:Found GPU.*compute capability:UserWarning
    ignore:.*with CUDA capability.*is not compatible:UserWarning
    ignore:.*_warn_unsupported_code:UserWarning
    ignore:The PyTorch API of nested tensors:UserWarning
